#pragma once

#include <frc/smartdashboard/SendableChooser.h>
#include <frc2/command/Command.h>

#include "subsystems/Drivetrain.h"
#include "subsystems/Leds.h"
#include "subsystems/AprilTags.h"

#include "commands/AutonomousCommand.h"
#include "commands/ChassisDrive.h"
#include "commands/DriveDistance.h"
#include "commands/SetLeds.h"

#include <frc/Joystick.h>
#include <frc2/command/button/JoystickButton.h>

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

class RobotContainer
{

public:
    frc2::Command         *GetAutonomousCommand();
    static RobotContainer *GetInstance();

    // The robot's subsystems
    Drivetrain m_drivetrain;
    Leds       m_leds;
    AprilTags  m_aprilTags;

    frc::Joystick *getJoystickOperator();
    frc::Joystick *getJoystickController();

private:

    RobotContainer();

    // Joysticks
    frc::Joystick m_joystickOperator{1};
    frc::Joystick m_joystickController{0};

    frc::SendableChooser<frc2::Command *> m_chooser;

    static RobotContainer *m_robotContainer;

    void ConfigureButtonBindings();
};